### 파이썬 리스트
: 가변형, 시퀀스(str,list,tuple) = [+,*, 중첩, 슬라이싱, 인덱싱],[]
-- 단점 : 동작속도가 느리다, 콤마 요소 분리 구별

### numpy : 수식 라이브러리, 수치 연산, 배열객체
-- 동작 속도가 빠르다./ 연속적인 메모리/ 한가지 타입만 처리가능

1) np.array로 객체생성
2) np.arange로 객체생성

In [10]:
# ndarray(shape[,dtype,buffer,offset,...])/ shape
import numpy as np


In [2]:
a = np.array([0,1,2,3,4,5]) # = ndarray 


In [3]:
print(a)
print(type(a))
print(a.dtype) # a객체가 가진 데이터 타입

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [6]:
print(dir(np.sctypeDict))
np.sctypeDict.keys() # numpay 에서 사용 되는 데이터 타입

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'ulong', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'float128', 'f16', 'complex64', 'c8', 'complex128', 'c16', 'complex256', 'c32', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'boo

In [9]:
a = np.array([0.0,1.0,2.0,3.0,4.0,5.0])
print(a)
print(type(a))
print(a.dtype) # a객체가 가진 데이터 타입  
#0,1 = bit * 8 = 1byte = 주소 생성 = -128 ~ 127
# 주소생성 -> 메모리 하당 -> 값 대입 
# 불리언 bool(1), byte(1)
# 정수형 short -> int32(4)->int64(8) -> long(8)~16
# 실수형 float(4)=float32 ->float(8)=f4->double(8)
# 문자와 문자열 ->str

# ex) 'int32' = 정수형 32 bit , 'i4'= 정수형 4byte
# float64 =f8 = 실수형 64bit =실수형 8byte


[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [13]:
a= np.arange(10) # 0~9 , 구분 하지 않는다
print(a)
print(type(a))


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [17]:
# 1차원 shape(x,)
a = np.arange(12)
print(a)
print(a.shape) # (12,) ->1차원
t= a.shape
print(type(t))
print((a.shape)[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
<class 'tuple'>
12


In [18]:
#2차원 배열의 Shape : 행(row, 수직, axis=0)과 열(column, 수평, axis=1)
m = np.array([[0,1,2],
             [0,1,2,]])
print(m)
print(m.shape)   # (2,3)---> 2차원, 행렬 (matrix)
print(m.shape[0],m.shape[1])

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


In [19]:
#3차원 배열의 shape :(면,행,열)
m = np.array([[
               [0,1,2],
               [3,4,5]],
               [[0,1,2],
                [3,4,5] ]])
print(m)
print(m.shape) # (2,2,3)---> 3차원
print(m.shape[0],m.shape[1],m.shape[2])

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)
2 2 3


In [20]:
# 2차원 배열 인덱싱 슬라이싱
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [23]:
#a 가 가진 값 0,0,9를 리턴해보자= 인덱싱
print(a[0][0])
print(a[0,0])
print(a[2][1])
print(a[2][3], a[2,3])


0
0
9
11 11


In [30]:
#a가 가진 슬라이싱
# [0 1 2 3]
print(a[0])
print(a[0,:]) #[행,열]

print(a[:,:-1]) # 마지막 열을 제외하겠다
print(a[:,1:])  # 첫번째 열을 제외하겠다
print('슬라이싱으로 전체 출력 형식을 만들자.')
print(a[:, :])
print(a[0:, 0:])


[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
슬라이싱으로 전체 출력 형식을 만들자.
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
# 0 행의 모든 데이터를 20으로 변경 후 전체 출력 해보자.
a[0]=20
print(a[:,:])
print(a[::2,::2]) #[start:end-1:step]

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 20]
 [ 8 10]]


In [34]:
# 슬라이싱 요소 전체의 값을 변경해보자.
print(a[:,:])
print(a[::2,::3])
a[::2,::3] =100
print(a[:,:])

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 20]
 [ 8 11]]
[[100  20  20 100]
 [  4   5   6   7]
 [100   9  10 100]]


In [35]:
#3차원 배열 인덱싱 슬라이싱
a= np.arange(12).reshape(2,2,3)
print(a, a.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [41]:
#인덱싱 
print(a[0][0][0])
print(a[0,0,0])
print(a[0,1,2])

0
0
5


In [62]:
#슬라이싱
print(a[:,:,:])#전체출력
print('----------------')
print(a[:,1:,1:])
print('----------------')


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
----------------
[[[ 4  5]]

 [[10 11]]]
----------------
[[[6 7]]]
[[[3]]]


In [66]:
#case 1: 3차원
#67
#45
print(a[1:,:-1,:2])
print(a[:-1,1:,1:])
print('----------------')
#case 2: 1차원
print(a[1,0,:2])
print(a[0,1,1:])
print('----------------')
#case 3:  3차원
print(a[1:,:1,:2])
print(a[:1,1:,1:])
print('----------------')
#case 4: 2차원
print(a[1,:-1,:-1],a[0,1:,1:])

[[[6 7]]]
[[[4 5]]]
----------------
[6 7]
[4 5]
----------------
[[[6 7]]]
[[[4 5]]]
----------------
[[6 7]] [[4 5]]


In [68]:
a= np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [70]:
print(a>2)
# 배열의 객체 a에서 2보다 큰값을 배열로 리턴
print(a[a>2]) #->이미지 ->빨간사과 ->이상값추출해서 변경하고싶을때

[False False  True  True  True  True]
[3 4 5 6]


In [72]:
boo1_index = np.array([False, False,  True,  True,  True,  True])
print(boo1_index)
print(a[boo1_index])

[False False  True  True  True  True]
[3 4 5 6]


In [83]:
# 배열 a에서 3이 아닌 요소 추출
print(a[a!=3])

# 2보다 크고 6보다 작은 요소 추출
print(a[(a>2) & (a<6)])

# 평균보다 작은 값을 추출해보자
print(a[a<a.mean()],a.mean())

[1 2 4 5 6]
[3 4 5]
[1 2 3] 3.5


In [86]:
#flatten() : 다차원 배열을 1차원으로 만든다
a=np.arange(12).reshape(3,4)
print(a,a.shape)
f = a.flatten()
print(f,f.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [88]:
#데이터 순서를 거꾸로 변경
print(a[::-1]) #행의 순서를 거꾸로 변경
print('-'*20)
print(a[:,::-1]) #열의 순서를 거꾸로 변경
print('-'*20)
print(a[::-1,::-1]) #행과 열의 순서를 거꾸로 변경

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
--------------------
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
--------------------
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [90]:
#transpose(): 전치 행열, 행과 열을 서로 맞바꾸는 함수
t=a.transpose()
print(t,t.shape) # (3,4)--->(4,3)
print(a.T) #transpose 함수와 동일한 결과

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [91]:
#print(dir(a.T))
a.flat = 0 # 임시로 1차원으로 변경후 값을 0으로 대입받고 차원을 다시 리턴한다
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [92]:
d = np.arange(12).reshape(3,4)
print(d,d.shape)
print(d.dtype)  # int32 or int64
print(d.ndim)   # 2차원  ==> print(len(d.shape)) 와 동일
print(d.T)      # transpose()함수와 동일한 결과, 전치행렬
print(d.size)   # 12개 , 요소의 갯수
print(d.nbytes) # 48 bytes : 32bit(4 byte) * 12 
d.flat = 1
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
int64
2
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
12
96
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [93]:
# numpy 통계 함수들
a = np.arange(12).reshape(3,4)
print(a, a.shape)
print(a.max(),np.max(a)) #최대값
print(a.min(),np.min(a)) #최소값

print(a.sum()) #합
print(a.mean())#평균 
print(a.std()) #표준편차
print(a.var()) #분산
print(np.median(a)) # 중위수

#사분위수
print('25%:',np.percentile(a,25)) #1사분위
print('50%:',np.percentile(a,50)) #2사분위 = meidan
print('75%:',np.percentile(a,75)) #3사분위


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
11 11
0 0
66
5.5
3.452052529534663
11.916666666666666
5.5
25%: 2.75
50%: 5.5
75%: 8.25
